# Generated by Django 5.0.6 on 2024-06-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
