# Generated by Django 5.0.6 on 2024-07-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaapp', '0002_house_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
